main merge request
tinatsina/online-kitchen pull request #64
Opened 2022-09-02 17:42 UTC by tinatsina

## Summary
- created an online kitchen as part of a project review
- this was done by three people
- also included AAA tests

## Features
- homepage with menus
- comment pop up with comments per food item
- reservation popup with reservations per food items

## API used
- used the `MealD API`
- you can access [MealD API](https://www.themealdb.com/api.php) here

## Contributors
- @tinatsina 
- @Suzi216 
- @MohamedCK 

## Video Link
[Loom Video Here](https://www.loom.com/share/f613c85e5ff2490ab17e36b6b292e2c8)

## Changelog
- `development` ---> `main`

## Live deployment
[View Page Here](https://tinatsina.github.io/online-kitchen/)

![Thor Shoulders](https://media.giphy.com/media/EfsqyinraWHCKWxsjq/giphy.gif)

2022-09-02 19:04 UTC, vickymarz requested changes
Hi @tinatsina , @MohamedCK , and @Suzi216  

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- All tests are passing ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 19:04 UTC, vickymarz commented on src/modules/displayComment.js
> +export const displayComment = async (index) => {
[OPTIONAL]

-For better user experience, I would recommend you implement an error message to display when a comment is not saved successfully and also a success message to show that a comment has been saved 👍🏽

2022-09-02 19:04 UTC, vickymarz commented on src/modules/displayReserv.js
> +  <input type="text" id="sdate" class="sdate" name="lname" value=""><br><br>
[OPTIONAL]

-For a better user experience, I would recommend you use a date input type so that a user can select the data instead of typing the date directly in a text input field. I think its exhausting typing dates 😄

2022-09-03 05:35 UTC, tinatsina commented on src/modules/eventHandlers.js
> +      currentLikeObject.innerHTML = (parseInt(currentLikeValue, 10) + 1);
Resolved 👍 
- used the return of a `try-catch` block to make sure only successful events are handled
- this only leaves an update if the `promise` fully resolves
- thanks for noticing 🤝

2022-09-03 05:37 UTC, tinatsina commented on src/modules/eventHandlers.js
> +      const currentLikeObject = item.nextSibling.nextElementSibling;
Resolved 👍 
- added an if-else statement for handling failure
- this allows the application to display `X` if failure to call API
- also means no increment happens
- thanks for noticing 🤝

2022-09-03 05:50 UTC, tinatsina commented on src/modules/reservationPopup.js
> +            <div class="card-container1"></div>
Resolved 👍 
- the problem was due to too many reservations listed.
- Added `inline-block` to allow the longer columns for reservations and comments
- made some minor `UI/UX` improvements 😄 
- thanks for noticing 🤝

2022-09-03 06:15 UTC, tinatsina commented on src/modules/displayMainPage.js
> +const displayMainPage = async () => {
Resolved 👍 
- used your advice and wrapped all API calls for the home page display in `try` and `catch ` `blocks`
- All `async `function calls are now wrapped around try and catch blocks
- also improved return results if the API calls are invalid

2022-09-03 14:02 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @Team :wave: :wave: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-05 01:40 UTC, merged